### ISSUE TITLE
It looks like you cloned bla. bla bla

### ISSUE THREAD

**Issue by hunnidxd** [cantryDev/CSGOCaseStatsViewer#19]
I didnt, i downloaded the newest version, and it just keeps saying the same thing over and over again :)

**Comment by rimwa** [comment]
Looking for more history entries
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: https://steamcommunity.com/my
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at de.cantry.casestatsfetcher.Utils.httpGet(Utils.java:32)
        at de.cantry.casestatsfetcher.Dumper.dumpFromTime(Dumper.java:50)
        at de.cantry.casestatsfetcher.Main.main(Main.java:47)
        
And then the download newest version bit
