### ISSUE TITLE
Issue with saying cloned repository

### ISSUE THREAD

**Issue by SpicyLemur** [cantryDev/CSGOCaseStatsViewer#20]
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at de.cantry.casestatsfetcher.Analyser.outPutStats(Analyser.java:43)
        at de.cantry.casestatsfetcher.Main.main(Main.java:55)

It looks like you cloned the repository instead of downloading the newest release.
Download it from https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest
You will be redirected to the download page in 20 seconds

**Comment by DjRicko** [comment]
Same error:
`java -jar CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar
Menu
1. -> Dump inventory history (can take some time)
2. -> Analyse case unboxing history
3. -> Analyse full CSGO history
Type the number and press enter.
2
Sorted by time
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at de.cantry.casestatsfetcher.Analyser.outPutStats(Analyser.java:43)
        at de.cantry.casestatsfetcher.Main.main(Main.java:55)

C:\Users\Ricko\Desktop\CSGOCaseStatsViewer-1.1.0>echo off
It looks like you cloned the repository instead of downloading the newest release.
Download it from https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest
You will be redirected to the download page in 20 seconds`

**Comment by scrubfn** [comment]
Same issue here.

D:\CSGOCaseStatsViewer-1.1.0 (2)>java -jar CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar
Menu
1. -> Dump inventory history (can take some time)
2. -> Analyse case unboxing history
3. -> Analyse full CSGO history
Type the number and press enter.
2
Sorted by time
Exception in thread "main" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Unknown Source)
        at de.cantry.casestatsfetcher.Analyser.outPutStats(Analyser.java:43)
        at de.cantry.casestatsfetcher.Main.main(Main.java:55)

D:\CSGOCaseStatsViewer-1.1.0 (2)>echo off
It looks like you cloned the repository instead of downloading the newest release.
Download it from https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest
You will be redirected to the download page in 20 seconds

Waiting for  0 seconds, press a key to continue ...
Press any key to continue . . .

**Comment by cedieasd** [comment]
downloaded the latest release but it says 

"It looks like you cloned the repository instead of downloading the newest release.
Download it from https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest
You will be redirected to the download page in 20 seconds"

**Comment by cantryDev** [comment]
Follow these Steps:
https://github.com/cantryDev/CSGOCaseStatsViewer#usage
