### ISSUE TITLE
cloned

### ISSUE THREAD

**Issue by Zec01** [cantryDev/CSGOCaseStatsViewer#21]
Looking for more history entries
Url:https://steamcommunity.com/id/ZEC01/inventoryhistory/
SessionId:e6d61d84166f0afbb3ea83f9
Exception in thread "main" java.io.IOException: Server returned HTTP response code: 429 for URL: https://steamcommunity.com/id/ZEC01/inventoryhistory/?ajax=1&cursor%5Btime%5D=99999999999&cursor%5Btime_frac%5D=0&cursor%5Bs%5D=0&sessionid=e6d61d84166f0afbb3ea83f9&app%5B%5D=730
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at de.cantry.casestatsfetcher.Utils.httpGet(Utils.java:32)
        at de.cantry.casestatsfetcher.Dumper.dumpFromTime(Dumper.java:66)
        at de.cantry.casestatsfetcher.Main.main(Main.java:47)

C:\Users\niroa\Desktop\CSGOCaseStatsViewer-1.1.0 (1)>echo off
It looks like you cloned the repository instead of downloading the newest release.
Download it from https://github.com/cantryDev/CSGOCaseStatsViewer/releases/latest
You will be redirected to the download page in 20 seconds

**Comment by JimiSUII** [comment]
Having this same issue no matter what i try

**Comment by Justeace** [comment]
Seems most people have the same issue. Wonder if we'll get a fix

**Comment by JimiSUII** [comment]
Uhh for me atleast, all i had to do to fix was open exec -> type ''1'' --> enter --> then enter cookie and boom it works.. i feel stupid

**Comment by All3b** [comment]
Fix: 
Step 1: When you get to the options after running "execute.bat" press 3.
            Step 1a. If you get auto redirected to the download without the ability to do anything, try downloading it from here  
                          https://github.com/cantryDev/CSGOCaseStatsViewer/releases/tag/1.1.0

Step 2: Paste your cookie, if you need help figuring out how to get your cookie 
            https://github.com/cantryDev/CSGOCaseStatsViewer/tree/1.1.0#chrome

Step 3: Let it finish, it might take a bit!

Step 4: Once it's done, close out of it. Should say something along the lines of
                    "  Open Result.html to see your results

                      C:\Folder Location>echo off
                      Press any key to continue . . .  "

Step 5: Open "Execute.bat"

Step 6: Press follow the instructions you get (It shouldn't redirect you to download now)

Step 7: ????

Step 8: Profit.


Just an fyi, I am in now way associated with the development of this, and this is just what I found to work, if you have any issues I can try  to help, but there's a 90% chance ill never check this again <3
