### ISSUE TITLE
Downloaded the latest release and opened execute.bat as an administrator as well.

### ISSUE THREAD

**Issue by davidsin02** [cantryDev/CSGOCaseStatsViewer#22]
Menu
1. -> Dump inventory history (can take some time)
2. -> Analyse case unboxing history
3. -> Analyse full CSGO history
Type the number and press enter.
2
Sorted by time
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at de.cantry.casestatsfetcher.Analyser.outPutStats(Analyser.java:43)
        at de.cantry.casestatsfetcher.Main.main(Main.java:55)

**Comment by cantryDev** [comment]
Dump the data first.
So press 1

**Comment by davidsin02** [comment]
> Dump the data first. So press 1

Oh I see, it worked after dumping data! Thank you
