### ISSUE TITLE
Out of memory and cant override

### ISSUE THREAD

**Issue by Pl8tinium** [cantryDev/CSGOCaseStatsViewer#31]
getting out of memory exception and the tool wont allow me to override the default values with

-Xms<size>
-Xmx<size>

....
Operation Phoenix Weapon Case
Operation Phoenix Weapon Case
2023-05-09T23:44:00Z
Event:You purchased an item on the Community Market.
+
Patch | Phoenix
-
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuffer.append(Unknown Source)
        at java.io.StringWriter.write(Unknown Source)
        at com.google.gson.stream.JsonWriter.string(JsonWriter.java:623)
        at com.google.gson.stream.JsonWriter.value(JsonWriter.java:426)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:749)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:763)
        at com.google.gson.internal.bind.TypeAdapters$28.write(TypeAdapters.java:697)
        at com.google.gson.internal.bind.TypeAdapters$34$1.write(TypeAdapters.java:913)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
        at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:126)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.toJson(Gson.java:747)
        at com.google.gson.Gson.toJson(Gson.java:726)
        at com.google.gson.Gson.toJson(Gson.java:681)
        at com.google.gson.Gson.toJson(Gson.java:661)
        at de.cantry.casestatsfetcher.AnalyserInventoryHistory.outPutStats(AnalyserInventoryHistory.java:150)
        at de.cantry.casestatsfetcher.Main.main(Main.java:59)

**Comment by lgmu** [comment]
Edit the first line in your execute.bat to this:

java -Xmx1G -jar CSGOCaseStatsViewer-1.1.0-jar-with-dependencies.jar

Then it worked without crashing for me

**Comment by Pl8tinium** [comment]
oh okay weird, i think if i set xms to a specific value it crashed, if i only use xmx it works, ty!
